- name: install nginx
  hosts: all
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed

    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: copy conf file
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: clean old content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create new directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory


    - name: download and extract
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes



